CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python3 run_training.py \
    --dataset_name HuggingFaceFW/fineweb-edu \
    --segment_len 512 \
    --sequence_length 4096 \
    --log_interval 1 \
    --batch_size 64 \
    --micro_batch_size 2 \
    --neural_memory_segment_len 64 \
    --neural_memory_batch_size 64 \
    --total_tokens 1000000000 \
    --intermittent_eval_frequency 50 \
    --intermittent_eval_limit 256 \
    --intermittent_eval_start_step 0 \
    --eval_interval 100
